#ifndef ENGINE_INCLUDE_ENTITIES_STRUCTS_ENGINE_INCLUDE_ENTITIES_STRUCTS_SPRITE_FLIP_H_
#define ENGINE_INCLUDE_ENTITIES_STRUCTS_ENGINE_INCLUDE_ENTITIES_STRUCTS_SPRITE_FLIP_H_

namespace engine::entities {

enum SpriteFlip {
  FlipNone, FlipHorizontal, FlipVertical, FlipHorizontalAndVertical
};

}

#endif //ENGINE_INCLUDE_ENTITIES_STRUCTS_ENGINE_INCLUDE_ENTITIES_STRUCTS_SPRITE_FLIP_H_
